#ifndef NETEQ_H
#define NETEQ_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Q14 scale factor: 2^14 = 16384
 *
 * This is the fundamental constant for Q14 fixed-point arithmetic.
 * All Q14 values are actual_value × SCALE.
 */
#define SCALE 16384.0

/**
 * Q14 scale factor as f32 for performance-critical conversions
 */
#define SCALE_F32 16384.0

typedef struct {
  uint32_t sample_rate;
  uint8_t channels;
  uintptr_t max_packets_in_buffer;
  uint32_t max_delay_ms;
  uint32_t min_delay_ms;
  uint32_t additional_delay_ms;
} NetEqConfigFfi;

void *neteq_create(NetEqConfigFfi config);

void neteq_destroy(void *neteq_ptr);

void neteq_get_audio_frame(void *neteq_ptr,
                           float *ret_buf,
                           uint32_t *timestamp_out,
                           uint16_t *seq_no_out);

void neteq_insert_audio_packet(void *neteq_ptr,
                               uint16_t sequence_number,
                               uint32_t timestamp,
                               uint8_t *payload,
                               uint32_t payload_len);

#endif  /* NETEQ_H */
